# Generated by Django 2.1.5 on 2019-01-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('tipoCocina', models.CharField(max_length=200)),
                ('alergenos', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=10)),
                ('tiempo', models.CharField(max_length=5)),
            ],
        ),
    ]
